version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/versions/cuda10.2-cudnn7"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda10.2-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.0.3-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.1.1-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.2.0-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.2.1-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.2.2-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.3.0-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.3.1-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.4.0-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  - package-ecosystem: "pip"
    directory: "/versions/cuda11.4.1-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
  - package-ecosystem: "pip"
    directory: "/versions/cuda11.4.2-cudnn8"
    schedule:
      interval: "daily"
    labels: ["dependabot"]
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
