pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - author=renovate[bot]
      - approved-reviews-by=@ml-image-maintainers
      - label=dependencies
      - label=update
      - base=master
      - 'check-success=build-push (cuda11.4.2-cudnn8)'
      - 'check-success=build-push (cuda11.4.1-cudnn8)'
      - 'check-success=build-push (cuda11.4.0-cudnn8)'
      - 'check-success=build-push (cuda11.3.1-cudnn8)'
      - 'check-success=build-push (cuda11.3.0-cudnn8)'
      - 'check-success=build-push (cuda11.2.2-cudnn8)'
      - 'check-success=build-push (cuda11.2.1-cudnn8)'
      - 'check-success=build-push (cuda11.2.0-cudnn8)'
      - 'check-success=build-push (cuda11.1.1-cudnn8)'
      - 'check-success=build-push (cuda11.0.3-cudnn8)'
      - 'check-success=build-push (cuda10.2-cudnn8)'
      - 'check-success=build-push (cuda10.2-cudnn7)'
    actions:
      merge:
        method: merge
