name: "test library version"
runs:
  using: "composite"
  steps:
    -
      name: Test library version
      shell: bash
      run: |
        docker run -u 1000 --rm \
          --volume $GITHUB_WORKSPACE/tests:/home/user/tests \
          --volume $GITHUB_WORKSPACE/Makefile:/home/user/Makefile \
          --env BASE_IMG_CUDA_VERSION="${{ env.base_img_cuda_version }}" \
          --env BASE_IMG_OS_VERSION="${{ env.base_img_os_version }}" \
          --env ANACONDA_VERSION="${{ env.anaconda }}" \
          --env OPENCV_VERSION="${{ env.opencv }}" \
          --env TF_GPU_VERSION="${{ env.tf_gpu }}" \
          --env KERAS_VERSION="${{ env.keras }}" \
          --env TORCH_VERSION="${{ env.torch }}" \
          --env TORCH_VISION_VERSION="${{ env.torch_vision }}" \
          --env TORCH_SUMMARY_VERSION="${{ env.torch_summary }}" \
          --env CUPY_CUDA_VERSION="${{ env.cupy_cuda }}" \
          --env CUDA_VERSION_FOR_CUPY="${{ env.cuda_version_for_cupy }}" \
          --env JUPYTER_VERSION="${{ env.jupyter }}" \
          --env NODEJS_VERSION="${{ env.nodejs }}" \
          --env TORCH_FILE="${{ env.torch_file }}" \
          --env TORCH_VISION_FILE="${{ env.torch_vision_file }}" \
          --env TF_TYPE="${{ env.tf_type }}" \
          --env OPTUNA_VERSION="${{ env.optuna }}" \
          --env PYENV_RELEASE_VERSION="${{ env.pyenv_release_version }}" \
          --env CONTAINER_VERSION="${{ env.container_version }}" \
          --env IMAGE_STATUS="${{ env.image_status }}" \
          "${{ env.container_image_name }}":"${{ env.container_version }}" \
          make unittest
