name: cuda11.0.3-cudnn8
env:
  image_status: "deprecated"
  container_version: "cuda11.0.3-cudnn8"
  anaconda: "2020.11"
  opencv: "4.5.1.48"
  tf_type: "tensorflow"
  tf_gpu: "2.4.3"
  keras: "2.4.3"
  torch: "1.8.0+cu111"
  torch_vision: "0.9.0+cu111"
  torch_summary: "1.5.1"
  cupy_cuda: "8.4.0"
  jupyter: "3.0.16"
  code_server: "3.9.1"
  rclone: "1.55.1"
  nodejs: "16"
  pyenv_release_version: "1.2.23"
  torch_file: "https://download.pytorch.org/whl/torch_stable.html"
  torch_vision_file: "https://download.pytorch.org/whl/torch_stable.html"
  github_token: ${{ secrets.GITHUB_TOKEN }}
on:
  pull_request:
    branches:
      - 'master'
    types: [opened, synchronize, reopened, closed]
    paths:
      - '.github/workflows/cuda11.0.3-cudnn8.yaml'
      - 'Dockerfile'
      - ".github/actions/**/*.yaml"
      - "configs/**/*"
      - "tests/**/*"
  schedule:
    - cron: "0 4 * * 1"
jobs:
  build-test:
    if: github.event.action != 'closed'
    runs-on: ubuntu-20.04
    env:
      container_image_name: "ghcr.io/kindaicvlab/machinelearning-images/test"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-env-vars
      - uses: ./.github/actions/show-version
      - uses: ./.github/actions/build-image
      - uses: ./.github/actions/test-version
  release-image:
    if: github.event.action == 'closed' || github.event_name == 'schedule'
    runs-on: ubuntu-20.04
    env:
      container_image_name: "ghcr.io/kindaicvlab/machinelearning-images"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-env-vars
      - uses: ./.github/actions/show-version
      - uses: ./.github/actions/build-image
      - uses: ./.github/actions/test-version
