name: cuda11.4.0-cudnn8
env:
  image_status: "feature"
  container_version: "cuda11.4.0-cudnn8"
  anaconda: "2021.05"
  opencv: "4.5.3.56"
  tf_type: "tf-nightly"
  tf_gpu: "2.7.0.dev20210818"
  keras: "2.6.0"
  torch: "1.10.0.dev20210818+cu111"
  torch_vision: "0.11.0.dev20210818+cu111"
  torch_summary: "1.5.1"
  cupy_cuda: "10.0.0b1"
  jupyter: "3.1.7"
  code_server: "3.11.1"
  rclone: "1.56.0"
  nodejs: "16"
  pyenv_release_version: "2.0.4"
  torch_file: "https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html"
  torch_vision_file: "https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-20.04
    env:
      container_image_name: "ghcr.io/kindaicvlab/machinelearning-images-test"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-env-vars
      - uses: ./.github/actions/show-version
      - uses: ./.github/actions/build-image
      - run: docker images ${{ env.container_image_name }}:${{ env.container_version }}
  release-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    env:
      container_image_name: "ghcr.io/kindaicvlab/machinelearning-images"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-env-vars
      - uses: ./.github/actions/show-version
      - uses: ./.github/actions/build-image
      - run: docker images ${{ env.container_image_name }}:${{ env.container_version }}
